# Site settings
remote_theme: raviriley/agency-jekyll-theme
url: ""
baseurl: ""
title: "Leuchtturmmomente"
email: josua.carl@web.de
description: "Trauerreden, die berühren und trösten"
author: "Josua Carl"
locale: "de-DE"

collections:
  portfolio:
  texts:
    output: true

markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-feed
